twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        vite_dev_url: 'http://localhost:5173'

when@test:
    twig:
        strict_variables: true