default:
  autoload:
    - "%paths.base%/bootstrap.php"

  extensions:
    FriendsOfBehat\SymfonyExtension:
      kernel:
        class: App\Kernel
        environment: test
        debug: true

  suites:
    delivery:
      paths:
        - behat/features/delivery
      contexts:
        - App\Behat\Common\DatabaseContext
        - App\Behat\Common\TenantContext
        - App\Behat\Common\JwtStorageContext
        - App\Behat\Common\HttpApiContext
        - App\Behat\Common\AuthJwtContext
        - App\Behat\Delivery\DeliveryWorkflowContext