default:
  autoload:
    - "%paths.base%/../bootstrap.php"

  extensions:
    FriendsOfBehat\SymfonyExtension:
      kernel:
        class: App\Kernel
        environment: test
        debug: false

  suites:
    warehouse:
      paths:
        - behat/features/warehouse
      contexts:
        - App\Behat\Common\DatabaseContext
        - App\Behat\Common\TenantContext
        - App\Behat\Common\JwtStorageContext
        - App\Behat\Common\HttpApiContext
        - App\Behat\Common\SeedContext
        - App\Behat\Common\AuthJwtContext
        - App\Behat\Warehouse\WarehouseWorkflowContext